spring:
  output:
    ansi.enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/lovely
    driver-class-name: org.postgresql.Driver
    username: muse
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379
application:
    security:
      jwt:
        expiration: 8640000
        secret-key: "snfdkvnd"


