spring:
  output:
    ansi.enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/lovely
    driver-class-name: org.postgresql.Driver
    username: muse
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: muse
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  redis:
    host: localhost
    port: 6379
application:
    security:
      jwt:
        expiration: 8640000
        secret-key: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"